sudo: required

language: python

python:
  - 3.6
  
services:
  - docker

before_install:
  - docker pull mercury/bissell
  - pip install codecov coverage

install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s irobotclient/tests
  - coverage combine
  - coverage report

after_success:
  - codecov

notifications:
  slack:
    secure: r0HPI6UOFdi8X+qdhTnZzDVwVynQKJeqrA/X/YqxfQXSBr1iNopTCmW+tXhWdBvImz7nbH+xwowtx8ZkV5mwlMG99gzr4oTnagxJO6PhbRxHxaU61JtpDYRrRM+x0OmvLLhXhfS2wsVXi8rq5G1Oe5+3SMtTDWV8Gun2AcLoCpGH10ZJMY5CFyJQ11zVxzMU90TVOxzJ85McXKf2KL8cD8gLY4oM0e5iaB91JC7PrEgJPsZRTWZtDsNk5SMsKVsyVcrmxyWINDCrqUzZkA1P0O+GPmylMjK/GuyOxZj59D0nJNwR1VJvRiR5qhLviqPNWA7x12UH8OV++RaSH429FFbRsOE29nHd45JF0cPUs7S6ok0GZC2eSXyETmlwUJyzS1sQBplb2i3PQnrJmaTA9zAC8Zvm9/en/GCcI1jefJXe4D5vVa++oOs3TdB0aoZ2GHdStGTEUwmnyKgurrtiOW1PLFwtnvVyLReXST5MPqYaGd+OspmYb85Gv597l/O3QxIVKLJAMHeg9Jfnj+ncNoNwBAV+b7BsRwimTvV6Uohg4o0EIxe3/6Iutn0QUB4eDaI1YYKWOJcyLI9nxJZ9yfJUeIQCrcgdOrNqLRGPt041wOVreTdlwj73jGxri1rbOIwfA6gcT4Pg7P+DFOna7+swKkRBQde5ElB6+l4azTI=
    
