sudo: required

language: python

python:
  - 3.6
  
services:
  - docker

before_install:
  - docker pull mercury/bissell
  - pip install codecov coverage

install:
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s irobotclient/tests
  - coverage setup.py install
  - coverage combine
  - coverage report

after_success:
  - codecov
